### ISSUE TITLE
Tags improvement

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#1304]
Enable users to copy and paste in the tag section.

- [x] 1. When users copy and paste words separated with a space or comma it should paste those words as tags.

- [x] 2. When users press (, comma)  while typing tags, it should jump to the next tag

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@horpey` in `#📲-esteem-mobile`.

**Comment by horpeyloaded** [comment]
I see this was improved, please make the tags switch to second line instead of user scrolling horizontally. I've suggested this but seems is not taking into account. Use busy.org and see the flexibility of tags. Scrolling tags to and fro is awkward than to fit in on the screen. If this can't be achieved with rounded box then remove the rounded box. Presently, the tag section is kind of a pain to users, check posts posted through eSteem app, you will notice some issues in users tags @feruzm
