### ISSUE TITLE
Beneficiary option

### ISSUE THREAD

**Issue by horpeyloaded** [ecency/ecency-mobile#1355]
Put the option to set beneficiaries on posts. Users are seriously requesting this feature and I suggest it should be added to next release.

**Comment by feruzm** [comment]
New users are not informed enough, I think it is good feature to have when we develop advanced editor settings, it will be instead of scheduling button and inside that modal page, user could schedule, change payout, change beneficiary settings, all under advanced settings without too much cluttering editor screen.

**Comment by feruzm** [comment]
done!
