### ISSUE TITLE
Feature: QR scan

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#2181]
On side menu have item for QR code, when clicked open screen with:

1. Ability to scan QR
2. Show QR with encoding username of logged in account if exist. This can be used for receiving funds.
3. On Transfer screens, `To` field/input should have QR icon next to it for scanning and quickly filling username.
4. Add logic for parsing QR encoding of different logic.
For example: `username:transfer` would open transfer screen with `To` field using `username`. `username:view` would open Profile page of `username`.  `username:boost` would open purchasing account boosting feature which we already have implemented.

**Comment by noumantahir** [comment]
@feruzm 
As an extension to this concept, we should also let users copy username or may be a direct menu is user profile to delegate/transfer etc.. 

because as we were discussing delegation screen with Sadaqat we realised it's not feasible for users to remember username, even though we now have autocomplete but that also require some effort from user itself which can be further improved

What do you think...?

**Comment by feruzm** [comment]
> we should also let users copy username or may be a direct menu is user profile to delegate/transfer etc..

Yes 💯  QR page will probably make it easier if your friend is nearby or even ability to share QR image, copy username, anything that makes day to day operations easier the better it is.
